/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Beginner guides",
      items: ["Installation", "Configuration"],
    },
    {
      type: "category",
      label: "API Reference",

      items: [
        "reference/Overview",

        {
          type: "category",

          label: "Components",
          items: [
            "reference/components/WFComponent",
            "reference/components/WFDynamicList",
            "reference/components/WFFormComponent",
            "reference/components/WFInvisibleForm",
          ],
        },
        {
          type: "category",
          label: "Routing",
          items: ["reference/routing/WFRoute"],
        },
        {
          type: "category",
          label: "Authentication",
          items: [
            "reference/auth/WFAuth",
            "reference/auth/WFAuthMiddleware",
          ],
        },

        {
          type: "category",
          label: "Utilities",
          items: [
            "reference/utils/onReady",
            "reference/utils/navigate",
            "reference/utils/createComponent",
          ],
        },
        {
          type: "category",
          label: "Data Services",
          items: [
            "reference/services/RESTAPIClient",
            "reference/services/GraphQLClient",
            // "reference/services/FireStoreClient",
            // "reference/services/SupabaseClient",
          ],
        },
      ],
    },
    // {
    //   type: "autogenerated",
    //   dirName: ".", // '.' means the current docs folder
    // },
  ],
};

module.exports = sidebars;
